In [6]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Boston Housing Dataset

In this project, I will use single-layer neural network to implement algorithm which predict the prices of houses in the Boston housing market.

**Dataset Description**

  * **CRIM**: per capita crime rate by town
  * **ZN**: proportion of residential land zoned for lots over 25,000 sq.ft.
  * **INDUS**: proportion of non-retail business acres per town
  * **CHAS**: Charles River dummy variable (=1 if tract bounds river; 0 otherwise)
  * **NOX**: nitric oxides concentraion (parts per 10 million)
  * **RM**: average number of rooms per dwelling
  * **AGE**: proportion of owner-occupied units built prior 1940
  * **DIS**: weighted distances to five Boston employment centres
  * **RAD**: index of accessibility to radial highways
  * **TAX**: full-value property-tax rate per \$10,000
  * **PTRATIO**: pupil-teacher raitio by town
  * **B**: 1000(Bk-0.63)^2, where Bk is the proportion of blacks by town
  * **LSTAT**: % lower status of the population
  * **MEDV**: median value of owner-occupied homes in $1000's

In [2]:
from sklearn.datasets import load_boston

boston = load_boston()

In [4]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

## Load Dataset

In [10]:
X = boston['data']
y = boston['target']

print(X.shape)
print(y.shape)

(506, 13)
(506,)

In [11]:
data = pd.DataFrame(X, columns = boston['feature_names'])
data['MEDV'] = y

print(data.shape)
data.head()

(506, 14)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

## Single Neural Network

### Gradient Descent (not using dot product)

In [12]:
x1 = X[:, 0] # CRIM
x2 = X[:, 1] # ZN
x3 = X[:, 2] # INDUS
x4 = X[:, 3] # CHAS
x5 = X[:, 4] # NOX
x6 = X[:, 5] # RM
x7 = X[:, 6] # AGE
x8 = X[:, 7] # DIS
x9 = X[:, 8] # RAD
x10 = X[:, 9] # TAX
x11 = X[:, 10] # PTRATIO
x12 = X[:, 11] # B
x13 = X[:, 12] # LSTAT

In [22]:
num_epoch = 100000
learning_rate = 0.000003

w1 = np.random.uniform(low=-1.0, high=1.0)
w2 = np.random.uniform(low=-1.0, high=1.0)
w3 = np.random.uniform(low=-1.0, high=1.0)
w4 = np.random.uniform(low=-1.0, high=1.0)
w5 = np.random.uniform(low=-1.0, high=1.0)
w6 = np.random.uniform(low=-1.0, high=1.0)
w7 = np.random.uniform(low=-1.0, high=1.0)
w8 = np.random.uniform(low=-1.0, high=1.0)
w9 = np.random.uniform(low=-1.0, high=1.0)
w10 = np.random.uniform(low=-1.0, high=1.0)
w11 = np.random.uniform(low=-1.0, high=1.0)
w12 = np.random.uniform(low=-1.0, high=1.0)
w13 = np.random.uniform(low=-1.0, high=1.0)
b = np.random.uniform(low=-1.0, high=1.0)

for epoch in range(num_epoch):
    y_predict = w1*x1 + w2*x2 + w3*x3 + w4*x4 + w5*x5 + w6*x6 + \
                w7*x7 + w8*x8 + w9*x9 + w10*x10 + w11*x11 + w12*x12 + w13*x13 + b
    
    error = np.abs(y_predict - y).mean()
    if error < 5:
        break
    
    if epoch % 10000 == 0:
        print('{0:5} error = {1:.5f}' .format(epoch, error))
        
    w1 = w1 - learning_rate * ((y_predict - y) * x1).mean()
    w2 = w2 - learning_rate * ((y_predict - y) * x2).mean()
    w3 = w3 - learning_rate * ((y_predict - y) * x3).mean()
    w4 = w4 - learning_rate * ((y_predict - y) * x4).mean()
    w5 = w5 - learning_rate * ((y_predict - y) * x5).mean()
    w6 = w6 - learning_rate * ((y_predict - y) * x6).mean()
    w7 = w7 - learning_rate * ((y_predict - y) * x7).mean()
    w8 = w8 - learning_rate * ((y_predict - y) * x8).mean()
    w9 = w9 - learning_rate * ((y_predict - y) * x9).mean()
    w10 = w10 - learning_rate * ((y_predict - y) * x10).mean()
    w11 = w11 - learning_rate * ((y_predict - y) * x11).mean()
    w12 = w12 - learning_rate * ((y_predict - y) * x12).mean()
    w13 = w13 - learning_rate * ((y_predict - y) * x13).mean()
    b = b - learning_rate * (y_predict - y).mean()    
    
print("---" * 10)
print("{0:5} error = {1:.5f}".format(epoch, error))

    0 error = 146.24437
10000 error = 6.41510
20000 error = 5.61832
30000 error = 5.28124
40000 error = 5.08326
------------------------------
46041 error = 4.99999

In [23]:
y_predict = w1*x1 + w2*x2 + w3*x3 + w4*x4 + w5*x5 + w6*x6 + \
            w7*x7 + w8*x8 + w9*x9 + w10*x10 + w11*x11 + w12*x12 + w13*x13 + b

result = data.copy()
result['MEDV(predict)'] = y_predict

print(result.shape)
result.head()

(506, 15)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,MEDV(predict)
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0,29.486872
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6,26.450159
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7,28.854937
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4,28.049161
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2,27.485330

### Gradient Descent (using dot product)

In [27]:
num_epoch = 100000
learning_rate = 0.000003

num_data = X.shape[0]

w = np.random.uniform(low=-1.0, high=1.0, size=13)
b = np.random.uniform(low=-1.0, high=1.0)

for epoch in range(num_epoch):
    y_predict = X.dot(w) + b
    
    error = np.abs(y_predict - y).mean()
    if error < 5:
        break
    if epoch % 10000 == 0:
        print("{0:5} error = {1:.5f}" .format(epoch, error))
    
    w = w - learning_rate * (y_predict - y).dot(X) / num_data
    b = b - learning_rate * (y_predict - y).mean()
    
print("----" * 10)
print("{0:5} error = {1:.5f}" .format(epoch, error))

    0 error = 250.75101
10000 error = 5.66897
20000 error = 5.11425
----------------------------------------
26670 error = 4.99999

In [28]:
y_predict = X.dot(w) + b

result = data.copy()
result["MEDV(predict)"] = y_predict

print(result.shape)
result.head()

(506, 15)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,MEDV(predict)
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0,28.695027
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6,25.842681
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7,27.563616
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4,27.447881
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2,27.189127

In [15]:
y_predict = X.dot(w) + b

result = data.copy()
result["MEDV(predict)"] = y_predict

print(result.shape)
result.head()

(506, 15)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,MEDV(predict)
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0,30.115258
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6,24.928269
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7,27.318432
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4,26.550113
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2,26.108157